### ISSUE TITLE
Doesn't build with Go 1.11

### ISSUE THREAD

**Issue by y0ssar1an** [minio/mc#2524]
## Expected behaviour
It should build.
## Actual behaviour
```sh
> cd $GOPATH/src/github.com/minio/mc
> make                                                                                                                                                  0
Checking dependencies
Checking for project in GOPATH
Building minio binary to './mc'
# github.com/minio/mc
github.com/minio/mc/vendor/golang.org/x/crypto/blake2b.supportsAVX2: relocation target runtime.support_avx2 not defined
github.com/minio/mc/vendor/golang.org/x/crypto/blake2b.supportsAVX: relocation target runtime.support_avx not defined
```
## Steps to reproduce the behaviour
1. Install Go 1.11
2. Run `make`
## mc version
Latest `master` commit: 3797227016af36a180bd40c35308319c6bd898d0

## System information
macOS 10.13.6
also fails in [official `golang:1.11` container](https://hub.docker.com/_/golang).

**Comment by kannappanr** [comment]
@y0ssar1an Thanks for filing this issue. We will try this one and provide a PR to fix this issue.

**Comment by y0ssar1an** [comment]
It appears the `golang.org/x/crypto` dependency is out of date. I tried updating it with `govendor`. It updated the `golang.org/x/sys` syscall package as well. Builds still failed with this error.
```
# github.com/minio/mc/vendor/golang.org/x/crypto/ssh/terminal
vendor/golang.org/x/crypto/ssh/terminal/util.go:30:12: undefined: unix.IoctlGetTermios
vendor/golang.org/x/crypto/ssh/terminal/util.go:38:18: undefined: unix.IoctlGetTermios
vendor/golang.org/x/crypto/ssh/terminal/util.go:54:12: undefined: unix.IoctlSetTermios
vendor/golang.org/x/crypto/ssh/terminal/util.go:64:18: undefined: unix.IoctlGetTermios
vendor/golang.org/x/crypto/ssh/terminal/util.go:75:9: undefined: unix.IoctlSetTermios
vendor/golang.org/x/crypto/ssh/terminal/util.go:80:13: undefined: unix.IoctlGetWinsize
vendor/golang.org/x/crypto/ssh/terminal/util.go:98:18: undefined: unix.IoctlGetTermios
vendor/golang.org/x/crypto/ssh/terminal/util.go:107:12: undefined: unix.IoctlSetTermios
vendor/golang.org/x/crypto/ssh/terminal/util.go:111:8: undefined: unix.IoctlSetTermios
```

**Comment by deekoder** [comment]
Pretty sure compiling with go1.10 and go 1.11 should not be a catch-22 situation. We will look into this and fix it @y0ssar1an .

**Comment by tk512** [comment]
I also have the same problem. Since Go 10.1 didn't work (the docs send you to this version but it gives another error), I had to download go 10.1.1.

**Comment by Zlogene** [comment]
same issue with all go interpriters existing in gentoo

**Comment by harshavardhana** [comment]
```
 prtsc : harsha : « » minio » mc : ⎇  master : go get -u golang.org/x/crypto/blake2b/...
 prtsc : harsha : « » minio » mc : ⎇  master : make pkg-update PKG=golang.org/x/crypto/blake2b/...
Updating new package golang.org/x/crypto/blake2b/...
 prtsc : harsha : « » minio » mc : ⎇  master : git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   vendor/golang.org/x/crypto/blake2b/blake2b.go
	modified:   vendor/golang.org/x/crypto/blake2b/blake2bAVX2_amd64.go
	modified:   vendor/golang.org/x/crypto/blake2b/blake2bAVX2_amd64.s
	modified:   vendor/golang.org/x/crypto/blake2b/blake2b_amd64.go
	modified:   vendor/golang.org/x/crypto/blake2b/blake2b_amd64.s
	modified:   vendor/vendor.json

no changes added to commit (use "git add" and/or "git commit -a")
 prtsc : harsha : « » minio » mc : ⎇  master : make install
Checking dependencies
Checking for project in GOPATH
Building minio binary to './mc'
Installing mc binary to '/home/harsha/mygo/bin/mc'
Installation successful. To learn more, try "mc --help".
 prtsc : harsha : « » minio » mc : ⎇  master
```
